spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/auth_service_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  liquibase:
    url: jdbc:postgresql://${DB_HOST}:5432/auth_service_db
    user: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: auth-service
    preferIpAddress: false
    
jwt:
  secret: ${JWT_SECRET}   
  expiration: ${JWT_EXPIRATION}
